on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build Name'
        default: 'Week-3-Build'
      output_path:
        description: 'Where to save (On the Runner machine)'
        default: 'C:\Users\Student\Desktop\MyBuilds'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          powershell -ExecutionPolicy Bypass -File .github/scripts/build.ps1 `
          -BuildName "${{ github.event.inputs.build_name }}" `
          -OutputPath "${{ github.event.inputs.output_path }}"
